#!/bin/bash
#
#::            S O F T W A R E    R E C I P I E S 
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#:: Author(s):   	SLS, KLS, NB.  Buffalo Center, IA & Avarua, Cook Islands
#:: Version 1.01
#::
#::
#::	Purpose: To define how software is added in one place. 
#::		 Software may be downloaded and installed manually, or via package manager or snaps. 
#::		 Configuration items are also defined here. 
#::     Usage: call this file using the "source" statment in bash. Then simply invoke the relevan recipie (funclion)
#:: 
#::     This script is shared in the hopes that
#::     someone will find it usefull.
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#	
#	NOTE:	This terminal program is written and documented to a very high degree. The reason for doing this is that
#		these apps are seldom changed and when they are, it is usefull to be able to understand why and how 
#		things were built. Obviously, this becomes a useful learning tool as well; for all people that want to 
#		learn how to write admin scripts. It is a good and necessary practice to document extensively and follow
#		patterns when building your own apps and config scripts. Failing to do so will result in a costly mess
#		for any organization after some years and people turnover. 
#
#		As a general rule, we prefer using functions extensively because this makes it easier to manage the script
#		and facilitates several users working on the same scripts over time.
#		
# 
#	RTD admin scrips are placed in /opt/rtd/scripts. Optionally scripts may use the common
#	functions in _rtd_functions and _rtd_recipies. 
#	  _rtd_functions -- contain usefull admin functions for scripts, such as "how to install software" on different systems. 
#	  _rtd_recipies  -- contain software installation and configuration "recipies". 
#	Scripts may also be stand-alone if there is a reason for this. 
#
#	Taxonomy of this script: we prioritize the use of functions over monolithic script writing, and proper indentation
#	to make the script more readable. Each function shall also be documented to the point of the obvious.
#	Suggested function structure per google guidelines:
#
#	function_name () {
#		# Documentation and comments... 
#		...code...
#	}
#
#	We also like to log all activity, and to echo status output to the screen in a frienly way. To accomplish this,
#	the table below may be used as appropriate: 
#
#				OUTPUT REDIRECTION TABLE	
#
#		  || visible in terminal ||   visible in file   || existing
#	  Syntax  ||  StdOut  |  StdErr  ||  StdOut  |  StdErr  ||   file   
#	==========++==========+==========++==========+==========++===========
#	    >     ||    no    |   yes    ||   yes    |    no    || overwrite
#	    >>    ||    no    |   yes    ||   yes    |    no    ||  append
#	          ||          |          ||          |          ||
#	   2>     ||   yes    |    no    ||    no    |   yes    || overwrite
#	   2>>    ||   yes    |    no    ||    no    |   yes    ||  append
#	          ||          |          ||          |          ||
#	   &>     ||    no    |    no    ||   yes    |   yes    || overwrite
#	   &>>    ||    no    |    no    ||   yes    |   yes    ||  append
#	          ||          |          ||          |          ||
#	 | tee    ||   yes    |   yes    ||   yes    |    no    || overwrite
#	 | tee -a ||   yes    |   yes    ||   yes    |    no    ||  append
#	          ||          |          ||          |          ||
#	 n.e. (*) ||   yes    |   yes    ||    no    |   yes    || overwrite
#	 n.e. (*) ||   yes    |   yes    ||    no    |   yes    ||  append
#	          ||          |          ||          |          ||
#	|& tee    ||   yes    |   yes    ||   yes    |   yes    || overwrite
#	|& tee -a ||   yes    |   yes    ||   yes    |   yes    ||  append
#
#	Our scripts are also structured in to three major sections: "settings", "functions", and "execute". 
#	Settings, contain configurable options for the script. Functions, contain all functions. Execute, 
#	contains all the actual logic and control of the script. 
#
#
#
# 	*		--- Installing software from the snap repository is prefferred --- 		*
#
# Snap is a software deployment and package management system developed by Canonical for the Linux operating system. 
# The packages, called snaps, and the tool for using them, snapd, work across a range of Linux distributions 
# allowing distribution-agnostic upstream software packaging. Snap application packages of software are self-contained 
# and work across a range of Linux distributions. This is unlike traditional Linux package  management approaches, 
# like APT or YUM, which require specifically adapted packages for each Linux distribution therefore adding delay between 
# application development and its deployment for end-users. 
#
# Supported distributions: 
# Arch Linux, CentOS, Debian, Fedora, Solus, Manjaro Linux, Linux Mint, OpenEmbedded, Raspbian, OpenWrt and openSUSE. 
#
# Security:
# Snaps are also contained from a security point of view and only have the access relly needed on a system. The user may
# add additional access descressionally. 
# 
# 	*	--- Installing software from the flathub repository is a secondary preferrence ---      *
#
# Flatpak (formerly xdg-app) is a software utility for software deployment and package management for Linux. It is advertised 
# as offering a sandbox environment in which users can run application software in isolation from the rest of the system.
# Applications using Flatpak need permissions to have access to Bluetooth, sound (with PulseAudio), network, files, etc., 
# permissions that are defined by the maintainer of the Flatpak and can be controlled (added or removed) by users on their 
# system.Flatpak was developed as part of the freedesktop.org project (formerly known as X Desktop Group or XDG) and was 
# originally called xdg-app.
#
# Flathub, a repository (or remote source in the Flatpak terminology) that is located at flathub.org, has become the de facto 
# standard for getting applications packaged with Flatpak.[9] Packages are added to it by both the Flathub administrators and 
# the developers of the programs themselves (though the admins have stated their preference for developer-submitted apps).
# Although Flathub is the de facto source for applications packaged with Flatpak, Flatpak can work independently of Flathub;
# it is possible to host a remote and access to remotes that are totally independent of Flathub.
#
#	*	---       Installing software from native distribution repositories  ----		*
#
# A Linux repository is a storage location from which your system retrieves and installs OS updates and applications. 
# Each repository is a collection of software hosted on a remote server and intended to be used for installing and updating 
# software packages on Linux systems. When you run commands such as “sudo apt update” or “sudo apt upgrade”, you may be pulling 
# package information and package updates from a number of repositories. 
# 
# For more information on package managers see: https://en.wikipedia.org/wiki/Package_manager
#
# THE Preferred way to manage native packages on Linux PackageKit. PackageKit is a free and open-source suite of software 
# applications designed to provide a consistent and high-level front end for a number of different package management systems.
# PackageKit simplifies how to manage software on several different linux distribution and may even be available on BSD flavors. 


# Add several software items that are almost alwasys used 
# in one way or another... 




recipie_baseapps (){
		# Add several software items that are almost alwasys used 
		# in one way or another... 
			echo -e $YELLOW"--- Adding some minor congiguration items for productivity..." $ENDCOLOR
			for i in diodon gnome-twitch polari filezilla 
			do
			     InstallSoftwareFromRepo $i
			done
			recipie_vivaldi
}


recipie_vivaldi (){

	if cat "/etc/os-release" | grep "debian" ; then
		dl https://downloads.vivaldi.com/stable/vivaldi-stable_2.10.1745.27-1_amd64.deb
	elif cat "/etc/os-release" | grep "fedora" ; then
		dl https://downloads.vivaldi.com/stable/vivaldi-stable_2.10.1745.27-1_amd64.rpm
	elif  cat "/etc/os-release" | grep "suse" ; then
		dl https://downloads.vivaldi.com/stable/vivaldi-stable_2.10.1745.27-1_amd64.rpm
	fi
}

recipie_wine (){
			     InstallSoftwareFromRepo wine
}


recipie_simplenote (){
			# some small simple apps you will like... 
			check_dependencies snapd
			# A simple to use not taking app that auto syncs with the same app on any device.
			snap install simplenote 2>>$_ERRLOGFILE

}



recipie_dos (){
			# some small simple apps you will like... 
			check_dependencies snapd
			# A small app that allows you to use your old DOS software. 
			snap install dosbox-x  2>>$_ERRLOGFILE

}



recipie_screenshot (){
			# some small simple apps you will like... 
			check_dependencies snapd
			# Feature rich screenshot tool and screenshot annotation tool. Great for support.
			snap install screencloud  2>>$_ERRLOGFILE
			snap install flameshot-app 2>>$_ERRLOGFILE

}



recipie_wps_office () {
			# Download and install WPS Office (more like Microsoft Office) OSS from China... 
			dl http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb wps-office_11.1.0.8722_amd64.deb
}



recepie_oem_restricted_fonts () {
			# Download and install Trutype font pack... these are propietary and require passphrase to unlock. 
			wget -q --show-progress "https://www.dropbox.com/s/7n5dgltnddtrs9j/True_Type_Font_Pack.7z" -P /opt/rtd/cache/
			mkdir -p /usr/share/fonts/truetype/oem
			check_dependencies p7zip-full
			7z e -y /opt/rtd/cache/True_Type_Font_Pack.7z -o/usr/share/fonts/truetype/oem/

}



recipie_secure_communication () {
			check_dependencies snapd
			snap install signal-desktop 2>>$_ERRLOGFILE
			snap install telegram-desktop 2>>$_ERRLOGFILE


}



recipie_video_editing () {
			check_dependencies snapd
			snap install vidcutter 2>>$_ERRLOGFILE 
			recipie_openshot

}



recipie_lamp_software (){
			echo -e $YELLOW"--- Adding Developer Software: LAMP Stack..." $ENDCOLOR
			for i in apache2 mysql-server php libapache2-mod-php php-mcrypt php-mysql \
				phpmyadmin nodejs
			do
			     InstallSoftwareFromRepo $i
			done
			echo "Cofiguring apache to run Phpmyadmin"
			echo "Include /etc/phpmyadmin/apache.conf" >> /etc/apache2/apache2.conf
			a2enmod rewrite
			service apache2 restart
}



recipie_developer_software (){
			echo -e $YELLOW"--- Adding Developer Software Apps: IDE Tools and Compilers..." $ENDCOLOR
			for i in build-essential git
			do
			     InstallSoftwareFromRepo $i
			done
			check_dependencies snapd
			snap install atom --classic  2>>$_ERRLOGFILE
			snap install gitkraken 2>>$_ERRLOGFILE
}



recipie_compression_tools (){
			echo -e $YELLOW"--- Adding Comression Toolset (zip, 7zip rar etc.)..." $ENDCOLOR	
			for i in p7zip-full p7zip-rar rar zip 

			do
			     InstallSoftwareFromRepo $i
			done
}



recipie_games (){
			# Install games from native repositories... 
			echo -e $YELLOW"--- Adding Selection of Quality Games..." $ENDCOLOR
						
			# --- Install games available in SNAP repository --- 
			for i in supertuxkart 0ad warzone2100 supertuxkart marsshooter
			do
			     snap install $i
			done
			
			# --- Install games available in Flathub repository and not at Snapcrafters --- 
			check_dependencies flatpak
			
			# Add the flatpack repository if it down not already exist:
			flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
			
			# Add requested games:
			flatpak install flathub com.moddb.TotalChaos -y	--noninteractive
			flatpak install flathub com.viewizard.AstroMenace -y --noninteractive
			flatpak install flathub io.github.EndlessSky.endless-sky -y --noninteractive
			flatpak install flathub com.albiononline.AlbionOnline -y --noninteractive
			flatpak install flathub com.endlessnetwork.aqueducts -y --noninteractive
			flatpak install flathub de.billardgl.Billardgl -y --noninteractive
			flatpak install flathub org.naev.Naev -y --noninteractive
			
			# --- Install games available in repository only --- 
			for i in dreamchess armagetronad mesa-utils assaultcube openarena
			do
			     InstallSoftwareFromRepo $i
			done
}



recipie_steam () {
			# Install Valves Steam Client for gaming. 
			InstallSoftwareFromRepo steam
			if [ $? != 0 ]; then 
			
				if hash rpm &>/dev/null; then
					dl https://steamcdn-a.akamaihd.net/client/installer/steam.rpm
				elif hash apt &>/dev/null; then
				
					dl https://steamcdn-a.akamaihd.net/client/installer/steam.deb 
				else
					echo -e $RED
					echo "I am not sure how to find the Steam download for $(lsb_release -sd) "
					echo "Please try to download it manually and instrtall it from the website:"
					echo "https://store.steampowered.com/about/"
					echo -e $ENDCOLOR
				fi
			fi
}


recipie_admin_tools (){
			echo -e $YELLOW"--- OEM System Administrative Tools..." $ENDCOLOR
			# Loop through each item in this list of software and perform an install 
			# using the relevant packaging system. 
			for i in terminix nmap synaptic ssh gparted sshfs htop iftop nethogs vnstat ifstat dstat nload glances bmon \
				vim vim-scripts gufw variety remmina remmina-plugin-exec remmina-plugin-secret remmina-plugin-vnc remmina-plugin-nx  \
				remmina-plugin-spice remmina-plugin-xdmcp remmina-plugin-rdp remmina-plugin-telepathy  

			do
			     InstallSoftwareFromRepo $i
			done

}



recipie_java (){
			# Special case for installing Oracle Java...
			echo -e $YELLOW"--- Adding Oracle Java..." $ENDCOLOR
	        	# Add the Oracle Java repository and install the software. 
    	    		add-apt-repository ppa:linuxuprising/java -y  1>>$_LOGFILE 2>>$_ERRLOGFILE
     	   		apt-get update  1>>$_LOGFILE 2>>$_ERRLOGFILE
    	    		echo oracle-java11-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections && \
    	    		apt install -y oracle-java12-installer    1>>$_LOGFILE 2>>$_ERRLOGFILE
   	     		apt install -y oracle-java12-set-default  1>>$_LOGFILE 2>>$_ERRLOGFILE
}



recipie_bleachbit (){
			#Bleachbit
			echo -e $YELLOW"--- Bleachbit System Cleaning Tool..." $ENDCOLOR
			InstallSoftwareFromRepo bleachbit 
}



recipie_codecs (){
			echo -e $YELLOW"--- Install all the required multimedia codecs..." $ENDCOLOR
			# Auto accept microsoft corefonts eula
			echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | /usr/bin/debconf-set-selections
			for i in libdvdcss2 ffmpeg ubuntu-restricted-extras
			do
			     InstallSoftwareFromRepo $i
			done		
}



recipie_vlc (){
			#VLC Media Player
			echo -e $YELLOW"--- Installing VLC Media Player..." $ENDCOLOR
			InstallSoftwareFromRepo vlc
}



recipie_google_chrome (){
			# Special case for installing Google Chrome
			echo -e $YELLOW"--- Installing Google Chrome Browser from google directly..." $ENDCOLOR
			dl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb google-chrome-stable_current_amd64.deb 1>>$_LOGFILE 2>>$_ERRLOGFILE
}



recipie_teamviewer (){
			#Teamviewer
			echo -e $YELLOW"--- Installing Teamviewer..." $ENDCOLOR
			dl https://download.teamviewer.com/download/linux/teamviewer_amd64.deb teamviewer_amd64.deb 1>>$_LOGFILE 2>>$_ERRLOGFILE
}



recipie_anydesk () {
			check_dependencies flatpak
			flatpak install flathub com.anydesk.Anydesk --noninteractive -y 

}



recipie_skype (){
			#Skype for Linux
			echo -e $YELLOW"--- Installing Skype For Linux..." $ENDCOLOR
			check_dependencies snapd
			snap install skype --classic  2>>$_ERRLOGFILE
}



recipie_viber (){
			check_dependencies snapd
			snap install --edge viber-mtd 
}



recipie_mega.nz (){
			# Special case for installing MEGA nz file sync utility (better than Drop Box)...
			echo -e $YELLOW"--- Installing MEGA nz file crypto sync utility..." $ENDCOLOR
			
			# Reset & clear variables in case of incomplete cleanup... 
			FILE2GET=
			URL=
			
			if lsb_release -si | grep "Debian" ; then
				URL="https://mega.nz/linux/MEGAsync/$(lsb_release -si)_$(lsb_release -sr).0/amd64/megasync-$(lsb_release -si)_$(lsb_release -sr).0_amd64.deb"
				FILE2GET="megasync-$(lsb_release -si)_$(lsb_release -sr).0_amd64.deb"
			elif lsb_release -si | grep "Ubuntu" ; then
				URL="megasync-xUbuntu_`lsb_release -sr`_amd64.deb"
				FILE2GET="https://mega.nz/linux/MEGAsync/xUbuntu_`lsb_release -sr`/amd64/$FILE2GET"				
			elif lsb_release -si | grep "openSUSE" ; then
				URL="https://mega.nz/linux/MEGAsync/openSUSE_Leap_15.0/x86_64/megasync-openSUSE_Leap_15.0.x86_64.rpm"
				FILE2GET="megasync-openSUSE_Leap_15.0.x86_64.rpm"
			else
				echo -e $RED
				echo "I am not sure how to find the Mega sync download for $(lsb_release -sd) "
				echo "Please try to download it manually and instrtall it from the website:"
				echo "https://mega.nz/sync"
				echo -e $ENDCOLOR
			fi
			
			# If a known distributio was found and URL set, use "dl" function to install app...
			[[ ! -z "$URL" ]] && dl $URL $FILE2GET 1>>$_LOGFILE 2>>$_ERRLOGFILE
}



recipie_dropbox (){
			# Install Dropbox
			echo -e $YELLOW"--- Installing Dropbox Cloud Storage Sync..." $ENDCOLOR
			InstallSoftwareFromRepo nautilus-dropbox
}



recipie_openshot (){
			# Special case for installing Openshot video editor
			echo -e $YELLOW"--- Installing Openshot video editor..." $ENDCOLOR
			add-apt-repository -y ppa:openshot.developers/ppa 1>>$_LOGFILE 2>>$_ERRLOGFILE
			apt-get update 1>>$_LOGFILE 2>>$_ERRLOGFILE
			apt-get -y -qq --allow-change-held-packages --ignore-missing install openshot openshot-doc 1>>$_LOGFILE 2>>$_ERRLOGFILE

}



recipie_media_streamers (){
			echo -e $YELLOW"--- Installing Music Players and Audio Software..." $ENDCOLOR
			check_dependencies snapd
			snap install spotify  2>>$_ERRLOGFILE
			snap install google-play-music-desktop-player  2>>$_ERRLOGFILE
			snap install winds 2>>$_ERRLOGFILE

}



recipie_audio_tools (){
			check_dependencies snapd
			snap install picard  2>>$_ERRLOGFILE
}



recipie_virtualbox (){
			# Special case for installing VirtualBox
			echo -e $YELLOW"--- Installing VirtualBox if available..." $ENDCOLOR
			echo virtualbox virtualbox/module-compilation-allowed boolean true | /usr/bin/debconf-set-selections
			echo virtualbox virtualbox/delete-old-modules boolean true | /usr/bin/debconf-set-selections
			# Loop through each item in this list of softwar and perform an install 
			# using the relevant packaging system. 
			for i in virtualbox virtualbox-dkms virtualbox-ext-pack virtualbox-guest-additions-iso 
			do
			     InstallSoftwareFromRepo $i
			done	
			# Ensure that the current user can use USB etc... 			
			if id -nG "$SUDO_USER" | grep -qw "vboxusers"; then
			    echo      $SUDO_USER already belongs to vboxusers group
			else
			    usermod -G vboxusers -a $SUDO_USER 1>>$_LOGFILE 2>>$_ERRLOGFILE
			fi
}


recipie_OEM_config (){
			echo "Applying OEM Configuration..."
			#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
			#::::::::::::::                                          ::::::::::::::::::::::
			#::::::::::::::          Desktop Settings                ::::::::::::::::::::::
			#::::::::::::::                                          ::::::::::::::::::::::
			#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
			enable_firewall
			# Power managment profile
			check_dependencies tuned
			systemctl enable --now tuned
			tuned-adm profile balanced

			#Tune to virtual machine guest or tune according to hardware type::
			check_dependencies virt-what
			check_dependencies laptop-detect
			if virt-what ; then 
				echo "This is likely not running in a virtual machine."
				if laptop-detect ; then 
					tuned-adm profile powersave
				else
					tuned-adm profile desktop
				fi
			else 
				tuned-adm profile virtual-guest 
			fi

			# Apply tweaks to the UI based on desktop active
			if  ps -e |grep "gnome-shell"; then
				echo "Fonud the gnome UI on this system! Adding some customizations..."
				# Add wallpapers and set GNOME wallpaper... 
				recipie_set_gnome_wallpaper
				recipie_tweak_user_gnome_ui
				# Pecial case for Fedora: Add the gnome UI tweak tool... 
				if cat /etc/os-release |grep "Fedora" &>> $_LOGFILE; then
					# Enable the extra repositories in fedora to get access to the espected software.
					InstallSoftwareFromRepo fedora-workstation-repositories 
				fi
				InstallSoftwareFromRepo gnome-tweak-tool
			fi

			if  ps -e |grep "plasmashell" ; then
				echo "Detected KDE UI!" 
				
				# Download and Set Wallpaper... 
				RTDCP="${_RTDCACHE:="/opt/rtd/cache"}"
				echo Downloading Wallpapers:
					mkdir -p $RTDCP && wget -q --show-progress https://github.com/vonschutter/RTD-Media/archive/master.zip -P $RTDCP && unzip -q -o $RTDCP/master.zip -d $RTDCP
					rm $RTDCP/master.zip
					pushd $RTDCP && mv -f RTD-Media-master/Wallpaper .. && mv -f RTD-Media-master/Sound .. 
				rtd_oem_kde_set_wallpaper "/opt/rtd/Wallpaper/Wayland.jpg" 

				# Download HQ Icons
				dl http://packages.linuxmint.com/pool/main/m/mint-y-icons/mint-y-icons_1.3.7_all.deb 

				lookandfeeltool -a 'org.kde.breezedark.desktop'
			
			fi
}







run_command_in_gnome_user_session () {
			# Function to do a reverse sudo back to teh original Gnome user who called upon sudo.
			# This functon expects any number of parameters that would make up the command or commands
			# to be run in the users session. For example:
			# 	run_command_in_gnome_user_session script_name.sh --parameter --one --two --etc
			#
			echo -------------------------- Begin as user: $SUDO_USER ---------------------
			echo "$@"
			sudo -H -u $SUDO_USER DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$SUDO_USER")/bus $@ > /dev/null 2>&1
			echo " "
			echo -------------------------- End as user: $SUDO_USER   ---------------------
}

recipie_tweak_user_gnome_ui (){
			# Configure Gnome for OEM look and feel. This is completely as desired. 
			# These setings will then be copied to the "/etsc/skel" directory where user templates
			# are stored. This will allow new users to get the same themes and settings as the 
			# current user. This should likely only be done right after a PC has been installed
			# otherwise all user configuration settings will be trasferred to any user 
			# subsequently created.  
			# Special case for installing Google Chrome
			echo -e $YELLOW"--- Optimizig look and feel of the desktop for productivity and aestetics..." $ENDCOLOR

				# Add Some clean and basic themes and icons...			
				for i in numix-gtk-theme numix-icon-theme numix-icon-theme-circle numix-icon-theme-square	\
					gnome-shell-extension-appindicator \
					gnome-shell-extension-suspend-button \
					gnome-shell-extension-log-out-button  \
					gnome-shell-extension-multi-monitors \
					gnome-shell-extension-caffeine \
					gnome-shell-extension-gsconnect  \
					gnome-shell-extension-gsconnect-browsers \
					gnome-shell-extension-dash-to-panel \
					gnome-shell-extension-dashtodock \
					arc-theme \
					adwaita-icon-theme-full adwaita-qt  
				do 
					InstallSoftwareFromRepo $i
				done

				dl http://packages.linuxmint.com/pool/main/m/mint-y-icons/mint-y-icons_1.3.7_all.deb 

			cat >> gtweak.sh <<-'EOF'
			#!/bin/bash
			# Terminal and Tilix Dark Theme
			 gsettings set com.gexperts.Tilix.Settings theme-variant 'dark'
			 gsettings set org.gnome.Terminal.Legacy.Settings theme-variant 'dark'
			 gsettings set org.gnome.Terminal.Legacy.Profile:/ use-transparent-background true
			 gsettings set org.gnome.Terminal.Legacy.Profile:/ background-transparency-percent 50
			 gsettings set org.gnome.Terminal.Legacy.Profile:/ background-color '#FFFFFF'
			 gsettings set org.gnome.Terminal.Legacy.Profile:/ highlight-background-color '#000000'
			 gsettings set org.gnome.Terminal.Legacy.Profile:/ default-size-columns 100
			 gsettings set org.gnome.Terminal.Legacy.Profile:/ use-theme-transparency false
			 gsettings set org.gnome.Terminal.Legacy.Profile:/ scrollback-lines 10000


			# Gnome Shell Theming
			# Add proffessional and crisp looking UI...
			 gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Darker'
			 gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'

			# Set font
			# gsettings set org.gnome.desktop.interface monospace-font-name 'Source Code Pro Semi-Bold 12'

			#Set Extensions for gnome
			 gsettings set org.gnome.shell disable-user-extensions false
			 gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'TopIcons@phocean.net', 'dash-to-dock@micxgx.gmail.com']"

			#Better Font Smoothing
			 gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'

			#Usability Improvements
			 gsettings set org.gnome.desktop.peripherals.mouse accel-profile 'adaptive'
			 gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
			 gsettings set org.gnome.desktop.calendar show-weekdate true
			 gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
			 gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'
			 gsettings set org.gnome.shell.overrides workspaces-only-on-primary false

			# Configure Dash to Dock
			 gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
			 gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
			 gsettings set org.gnome.shell.extensions.dash-to-dock apply-custom-theme false
			 gsettings set org.gnome.shell.extensions.dash-to-dock custom-background-color false
			 gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-customize-running-dots true
			 gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-color '#729fcf'
			 gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-shrink true
			 gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
			 gsettings set org.gnome.shell.extensions.dash-to-dock extend-height true
			 gsettings set org.gnome.shell.extensions.dash-to-dock force-straight-corner false
			 gsettings set org.gnome.shell.extensions.dash-to-dock icon-size-fixed true
			 gsettings set org.gnome.shell.extensions.dash-to-dock intellihide-mode 'ALL_WINDOWS'
			 gsettings set org.gnome.shell.extensions.dash-to-dock isolate-workspaces true
			 gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
			 gsettings set org.gnome.shell.extensions.dash-to-dock unity-backlit-items false
			 gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode 'FIXED'
			 gsettings set org.gnome.shell.extensions.dash-to-dock running-indicator-style 'SEGMENTED'
			 gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0.70000000000000000
			 gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
			 gnome-shell-extension-tool -e dash-to-dock


			#This indexer is nice, but can be detrimental for laptop users battery life
			 gsettings set org.freedesktop.Tracker.Miner.Files index-on-battery false
			 gsettings set org.freedesktop.Tracker.Miner.Files index-on-battery-first-time false
			 gsettings set org.freedesktop.Tracker.Miner.Files throttle 15

			#Nautilus (File Manager) Usability
			 gsettings set org.gnome.nautilus.icon-view default-zoom-level 'standard'
			 gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'
			 gsettings set org.gtk.Settings.FileChooser sort-directories-first true
			 gsettings set org.gnome.nautilus.list-view use-tree-view true
			 gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'

			# Set the GNOME Shell Apps Dashboard sort app in categories based on the FreeDesktop standard.
			 gsettings set org.gnome.desktop.app-folders folder-children "['accessories', 'chrome-apps', 'games', 'graphics', 'internet', 'office', 'programming', 'science', 'sound---video', 'system-tools', 'universal-access', 'wine']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/accessories/ name "Accessories"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/accessories/ categories "['Utility']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/chrome-apps/ name "Chrome Apps"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/chrome-apps/ categories "['chrome-apps']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/games/ name "Games"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/games/ categories "['Game']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/graphics/ name "Graphics"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/graphics/ categories "['Graphics']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/internet/ name "Internet"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/internet/ categories "['Network', 'WebBrowser', 'Email']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/office/ name "Office"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/office/ categories "['Office']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/programming/ name "Programming"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/programming/ categories "['Development']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/science/ name "Science"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/science/ categories "['Science']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/sound---video/ name "Sound & Video"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/sound---video/ categories "['AudioVideo', 'Audio', 'Video']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/system-tools/ name "System Tools"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/system-tools/ categories "['System', 'Settings']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/universal-access/ name "Universal Access"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/universal-access/ categories "['Accessibility']"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/wine/ name "Wine"
			 gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/wine/ categories "['Wine', 'X-Wine', 'Wine-Programs-Accessories']"
			EOF

	run_command_in_gnome_user_session /bin/bash gtweak.sh 
}



recipie_set_gnome_wallpaper (){
			# Install Wallpapers and configure Gnome to see them. ...
			RTDCP=/opt/rtd/cache
			echo Downloading Wallpapers:
			echo ---------------------------------------------
			mkdir -p $RTDCP && wget -q --show-progress https://github.com/vonschutter/RTD-Media/archive/master.zip -P $RTDCP && unzip -q -o $RTDCP/master.zip -d $RTDCP
			rm $RTDCP/master.zip
			pushd $RTDCP && mv -f RTD-Media-master/Wallpaper .. && mv -f RTD-Media-master/Sound .. 
			echo ---------------------------------------------
			mkdir -p /usr/local/share/gnome-background-properties
			DIRECTORY=/opt/rtd/Wallpaper/
			ls $DIRECTORY > lspictures.txt

			# Make a header
			echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
			<!DOCTYPE wallpapers SYSTEM \"gnome-wp-list.dtd\">
			<wallpapers>" > mybackgrounds.xml
			# Registering all pictures in $DIRECTORY

				for i in $DIRECTORY*.jpg $DIRECTORY*.png; do
				echo "<wallpaper>
				<name>$i</name>
				<filename>$i</filename>
				  <options>stretched</options>
				    <pcolor>#8f4a1c</pcolor>
				    <scolor>#8f4a1c</scolor>
				    <shade_type>solid</shade_type>
				  </wallpaper>" >> mybackgrounds.xml
				done

			# creating the footer
				echo "</wallpapers>" >> mybackgrounds.xml
				sed 's/<name>\/usr\/share\/backgrounds\//<name>/g' mybackgrounds.xml > /usr/local/share/gnome-background-properties/mybackgrounds.xml
				# cp /usr/local/share/gnome-background-properties/mybackgrounds.xml /usr/share/gnome-background-properties/mybackgrounds.xml
				rm mybackgrounds.xml
				rm lspictures.txt
			# Set the default wallpaper... 
				run_command_in_gnome_user_session gsettings set org.gnome.desktop.background picture-uri file:///opt/rtd/Wallpaper/Wayland.jpg


}
