#!/bin/bash
#
#::                                    A D M I N   C O M M A N D
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
#::
#:: Author:   	SLS
#:: Version 	1.02
#::
#::
#::	Purpose: The purpose of this script is to do som cleaning of iptables.
#::		 This may be useful in troubleshooting.
#::
#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
#::
#::
#::
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
#
# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it useful.
#
# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.

###########################################################################
##                                                                       ##
##                       Commandlet settings                             ##
##                                                                       ##
###########################################################################

# Elevate the privileges to root equivalent (if not already) to manage system...

if [ ! "$UID" -eq 0 ]; then
        if hash dialog 2>/dev/null ; then
                # find  a diferent way... tempfile not universal...
                data=$(tempfile 2>/dev/null)
                trap "rm -f $data" 0 1 2 5 15
                dialog --title "${Title}" --backtitle "${BackTitle}" --insecure --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90 2> $data
                ret=$? ; clear
                case $ret in
                        0) cat $data | sudo -S bash "$0" "$*" ;;
                        1) echo "Request cancelled" ;;
                        255) [ -s $data ] && rm $data &>/dev/null || echo "[esc] Request aborted" ;;
                        * ) rm $data &>/dev/null ; exit 1
                esac
                rm $data &>/dev/null
                exit
        else
                [ "$UID" -eq 0 ] || echo "This script needs administrative access..."
                [ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"
        fi
fi


###########################################################################
##                                                                       ##
##                         Execute                                       ##
##                                                                       ##
###########################################################################




iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

