#!/bin/bash
RTD_UPDATE_SELF_VERSION=1.0
#::
#::
#:: 					Update RTD admin tools Task Sequence

#::                                     A D M I N   C O M M A N D
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
#:: Author(s):   	SLS, KLS, NB.  Buffalo Center, IA & Avarua, Cook Islands
#:: Version:	1.00
#::
#::
#:: Purpose: 	The purpose of the task sequence is to configure update the installed admin tools.
#::
#::
#::		This task sequence should be executed on a PC with the the RTD OEM installation or configuration
#::
#::
#::
#:: Background: This system configuration and installation script was created to facilitate geting the latest simple
#::             managment tools on to a computer already using the rtd tools.
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
#
#	RTD admin scrips are placed in /opt/rtd/scripts. Optionally scripts may use the common
#	functions in _rtd_functions and _rtd_recipies.
#	  _rtd_functions -- contain usefull admin functions for scripts, such as "how to install software" on different systems.
#	  _rtd_recipies  -- contain software installation and configuration "recipies".
#	Scripts may also be stand-alone if there is a reason for this.



#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Settings                 ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Variables that govern the behavior or the script and location of files are

# Base folder structure for optional administrative commandlets and scripts:
_RTDSCR=$(if [ -f /opt/rtd/scripts ]; then echo /opt/rtd/scripts ; else ( mkdir -p /opt/rtd/scripts & echo  /opt/rtd/scripts ) ; fi )
_RTDCACHE=$(if [ -f /opt/rtd/cache ]; then echo /opt/rtd/cache ; else ( mkdir -p /opt/rtd/cache & echo  /opt/rtd/cache ) ; fi )
_RTDLOGSD=$(if [ -f /opt/rtd/log ]; then echo /opt/rtd/log ; else ( mkdir -p /opt/rtd/log & echo  /opt/rtd/log ) ; fi )

# Location of base administrative scripts and commandlets to get.
_RTDSRC=https://github.com/vonschutter/RTD-Build/archive/master.zip

BRAND=RTD

#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Functions                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

check_rtd_library ()
{
        # Set library path if not defined:
        rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}

        if [[ -f ${rtd_library} ]]; then
                source ${rtd_library}
        elif [[ ! -f ${rtd_library} ]]; then
                echo "RTD Functions not found... "
                echo "Trying to retrieve them..."
                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
                source ./_rtd_library
        else
                exit 1
        fi
}

task_setup_rtd_basics() {
	echo "Task: Attempting to get the latest RTD tools..."
	[[ -f $_RTDCACHE/master.zip ]] && rm -f $_RTDCACHE/master.zip || echo "No cashed content found..."
	wget -q --show-progress $_RTDSRC -P $_RTDCACHE
	unzip -o -j -q $_RTDCACHE/master.zip -d $_RTDSCR  -x *.png *.md *.yml *.cmd
	if [ $? != 0 ]; then
		echo -e $RED Sorry but I think I FAILED to get the latest updates! $ENDCOLOR
		exit 1
	else
		echo "Task: Instructions sucessfully retrieved..."
		chmod +x $_RTDSCR/*
		pushd /bin
		echo "Updating executable links (to simplify running the tools)..."
		ln -f -s $_RTDSCR/rtd* .
		popd
	fi
}




rtd_wait_for_internet_availability () {
	echo "Waiting for internet access..."
	echo "NOTE: Free access to the internet is required to continue."
	while ! ping -c 1 -W 1 8.8.8.8 &>/dev/null ; do
		echo Waiting...
		sleep 5
	done
}



do_update ()
{
	rtd_wait_for_internet_availability
	task_setup_rtd_basics
	rtd_oem_make_launchers
}


#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Execute tasks                   ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

check_rtd_library
ensure_admin

if hash dialog ; then
	if ( dialog --backtitle "$( basename $0 )" --title "${BRAND} tools updater: NOTICE!" --yesno "May I update the ${BRAND} OEM tools on your system now? Updating the ${BRAND} tools will ensure that the lates functionality and bug fixes are applied. \n Press OK to continue or NO to skip doing this." 20 80 ) ; then
		clear && do_update
	else
		clear && exit
	fi
else
	echo -e $YELLOW
	echo "RTD Tools Updater Version $RTD_UPDATE_SELF_VERSION"
	echo "Hello $SUDO_USER ... I am going to update the rtd tools on this"
	echo " "
	echo "To cancel this, just close the terminal or press "CRTL C"."
	echo " "
	read -p "Press [ ENTER ] to continue with update"
	echo -e $ENDCOLOR
	do_update
fi



