#!/bin/bash
#
#::            A D M I N   C O M M A N D L E T   
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#:: Author:   	SLS  
#:: Version 	1.02
#::
#::
#::	Purpose: The purpose of this script is to do som cleaning of iptables. 
#::		 This may be useful in troubleshooting. 
#::		 
#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
#:: 		
#::     	
#::     	
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
#
# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it useful.
#
# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.

###########################################################################
##                                                                       ##
##                       Commandlet settings                             ##
##                                                                       ##
###########################################################################

# Elevate the privileges to root equivalent (if not already) to manage system...
[ "$UID" -eq 0 ] || echo "This script needs administrative access..."
[ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"


###########################################################################
##                                                                       ##
##                         Execute                                       ##
##                                                                       ##
###########################################################################




iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

