#!/bin/bash

# Lunches 4 Xterm windows and starts system monitoring tool in them.
#
# Xterm obeys the following on screen positions:
#
# +0+0    upper left hand corner.
# -0+0    upper right hand corner.
# -0-0    lower right hand corner.
# +0-0    lower left hand corner.


xterm  -geometry 110x30+0+0 -e htop&
xterm  -geometry 110x30-0+0 -e 'tail -f /var/log/syslog' &
xterm  -geometry 110x30-0-0 -e 'watch df -h '&
xterm  -geometry 110x30+0-0 -e 'bmon' &
