#!/bin/bash
#
#	RTD Ubuntu Scripts
#   	Stephan S.
#
#
# Version 1.00
#
# This script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it usefull.
#
# This script is instended to live in the ~/bin/ folder.

#find ./ -type f -iname "*.rar" -exec unrar e {} \;


list=`find ./ -type f -name "*.rar"`
for line in $list; do
DEST=${line%/*}
unrar x $line $DEST
done
