#!/bin/bash
#
#::             			A D M I N   C O M M A N D L E T   
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// Simple bootable CD/DVD creation Tool //:::::::::::::::::::::// Linux //::::::::
#::
#:: Author:   	SLS  
#:: Version 	1.00
#::
#::
#::	Purpose: The purpose of the script is to write an ISO file to an optical device verbatim. 
#::		  
#::		 
#::     Usage:	Simply execute this commandlet passing the parameter indicating where the ISO is located 
#:: 		to accomplish this task. 
#::     	
#::     	Example: 
#::		rtd-burniso path/to/file.iso
#::     	
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
# Additional information: 
#
# An ISO image is a disk image of an optical disc. In other words, it is an archive file that contains everything that would 
# be written to an optical disc, sector by sector, including the optical disc file system.[1] ISO image files bear the .iso 
# filename extension. The name ISO is taken from the ISO 9660 file system used with CD-ROM media, but what is known as an 
# ISO image might also contain a UDF (ISO/IEC 13346) file system (commonly used by DVDs and Blu-ray Discs).
#
# ISO images can be created from optical discs by disk imaging software, or from a collection of files by optical disc authoring 
# software, or from a different disk image file by means of conversion. Software distributed on bootable discs is often available 
# for download in ISO image format. And like any other ISO image, it may be written to an optical disc such as CD or DVD. 
#
# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it useful.
#
# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
#


#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Settings                 ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

# Set colors for prompting on screen.
	YELLOW="\033[1;33m"
	RED="\033[0;31m"
	ENDCOLOR="\033[0m"
	GREEN="\033[0;32m"
	BLUE="\033[0;34m"


if [ -f ~/bin/_rtd_functions ]; then 
	source ~/bin/_rtd_functions
else 
	if -f [ /opt/rtd/scripts/_rtd_functions ]; then 
		source /opt/rtd/scripts/_rtd_functions
	else 
		echo "RTD Functions not found... "
		echo "Trying to retrieve them..."
		wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_functions 
		source ./_rtd_functions
	fi
fi



if [[ "$RTDFUCTIONS" = "1" ]]
      then
        echo -e $GREEN "RTD functions loaded!" $ENDCOLOR
      else
        echo -e $RED "RTD functions NOT loaded!" $ENDCOLOR
        echo -e $YELLOW " " $ENDCOLOR
        echo -e $YELLOW "Cannit ensure that the correct software is available" $ENDCOLOR
        echo -e $YELLOW "Quiting rather than cause potential damage..." $ENDCOLOR
        exit 1
fi


###########################################################################
##                                                                       ##
##                       Script Executive                                ##
##                                                                       ##
###########################################################################
check_dependencies mencoder
check_dependencies dialog


rtd_join_avis () {
        mencoder -oac copy -ovc copy *.avi -o WHOLE-THING.avi
}


rtd_join_avis
 
