#!/bin/bash
#
#::                                          A D M I N   C O M M A N D
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// System managment Setup Script //::::::::::::::::::::::::::::// Ubuntu //:::::::
#::
#:: Author:   	SLS
#:: Version 	1.00
#::
#::
#::	Purpose: The purpose of the script is to install and configure landscape for ubuntu so it can be managed from
#::		 a single location.
#::
#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
#:: 		Then, when prompted; enter the information requested.
#::
#::     	To understand how t use Landscape please refer to: https://landscape.canonical.com/
#::
#::
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
#
# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it useful.
#
# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
#


#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Settings                 ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

# Set default UI colors:
YELLOW="\033[1;33m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

# Set library path if not defined:
rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}

if [ ! "$UID" -eq 0 ]; then
        if hash dialog 2>/dev/null ; then
                # find  a diferent way... tempfile not universal...
                data=$(tempfile 2>/dev/null)
                trap "rm -f $data" 0 1 2 5 15
                dialog --title "${Title}" --backtitle "${BackTitle}" --insecure --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90 2> $data
                ret=$? ; clear
                case $ret in
                        0) cat $data | sudo -S bash "$0" "$*" ;;
                        1) echo "Request cancelled" ;;
                        255) [ -s $data ] && rm $data &>/dev/null || echo "[esc] Request aborted" ;;
                        * ) rm $data &>/dev/null ; exit 1
                esac
                rm $data &>/dev/null
                exit
        else
                [ "$UID" -eq 0 ] || echo "This script needs administrative access..."
                [ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"
        fi
fi



#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Functions                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

check_rtd_library ()
{
        if [[ -f ${rtd_library} ]]; then
                source ${rtd_library}
        elif [[ ! -f ${rtd_library} ]]; then
                echo "RTD Functions not found... "
                echo "Trying to retrieve them..."
                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
                source ./_rtd_library
        else
                exit 1
        fi
}

#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::          Script Executive                ::::::::::::::::::::::
#::::::::::::::                                          ::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

check_rtd_library
up2date
SofwareManagmentAvailabilityCHK
check_dependencies dialog

# The name of the local managment server
LOCALSERVER=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"$( basename $0 )"}" --stdout --inputbox "\n Please enter the name of the local landscaps server. \n " 10 90 )
LOCALSERVERIP=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"$( basename $0 )"}" --stdout --inputbox "\n Please enter the IP Address of the local landscap server. \n " 10 90 )
# Since landscape is only relevant for Ubuntu; its OK to you distro speciffic commands...
apt-get install landscape-client -y -q
echo "ssl_public_key = /etc/landscape/landscape_server_ca.crt" >>/etc/landscape/client.conf
write_status "---------------- clinet.conf  -----------"
cat /etc/landscape/client.conf
echo "${LOCALSERVERIP}       ${LOCALSERVER}" >>/etc/hosts
write_status "----------------  hosts -----------------"
cat /etc/hosts
write_status "---------  Get CA from ${LOCALSERVER} ---------"
echo Enter password for ${LOCALSERVER} below:
scp ${USER}@${LOCALSERVER}:/etc/landscape/*.crt /etc/landscape/
landscape-config --computer-title "${HOSTNAME}" --account-name standalone  -p ${PASSTOKEN} --url https://${LOCALSERVER}/message-system --ping-url http://${LOCALSERVER}/ping && result="Sucessfully enrolled with the lanscape server ${LOCALSERVER}" || result="Failed to enroll with the lanscape server ${LOCALSERVER}"
display_result "$( basename $0 )"

