#!/bin/bash
#
#	RTD Ubuntu Scripts
#   	Stephan S.
#
#
# Version 1.00
#
# This script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it usefull.
#
# This script is instended to live in the ~/bin/ folder.

pushd /home/stephans/DVD/
for f in `ls *.iso`
do
  echo "Processing $f file..."
  HandBrakeCLI -e x264 -b 3500 -B 160 -7 -R 48 -E aac+ac3 -f mp4 -4 -m -p -x bframes=3:ref=1:subme=5:me=umh:no-fast-pskip=1:trellis=1:cabac=0 -i $f -o ~/Videos/AppleTV/$f.m4v
  mv $f ~/DVD/Riped/
done
