#!/bin/bash
#
#::             			A D M I N   C O M M A N D L E T   
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::// Software Setup CMDLET //::::::::::::::::::::::::::::::::::::// Ubuntu //:::::::
#::
#:: Author:   	SLS  
#:: Version 	1.00
#::
#::
#::	Purpose: The purpose of the script is to install and configure landscape for ubuntu so it can be managed from
#::		 a single location. 
#::		 
#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
#:: 		Then, when prompted; enter the information requested.
#::     	
#::     	To understand how t use Landscape please refer to: https://landscape.canonical.com/
#::
#::     	
#::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
#
# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it useful.
#
# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
#
 

###########################################################################
##                                                                       ##
##                         Setup Environment                             ##
##                                                                       ##
###########################################################################
#
# elevate the privileges to root equivalent
YELLOW="\033[1;33m"
RED="\033[0;31m"
ENDCOLOR="\033[0m"

# he name of the local managment server (change to desired name)
LOCALSERVER=imhothep

echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

#
###########################################################################
##                                                                       ##
##                         Declare Functions                             ##
##                                                                       ##
###########################################################################
#
# Function to check and see if the system software managment is available
function SofwareManagmentAvailabilityCHK ()
{
echo Checking if software maintenance system is available...
while [ -f /var/lib/dpkg/lock ] ;
		do
			echo "The software managment system is locked..."
			echo "Waiting 10 seconds for software managment system to be ready:"
			for i in {0..100}; do echo -ne "$i"'\r'; sleep 1; done; echo
			echo "force unlocking package managment..."
			rm -f  /var/lib/apt/lists/lock
			rm -f /var/lib/dpkg/lock
	done
}

# Function to simplify updating system completely...
function up2date ()
{
	echo "Running up2date on behalf of $0"
	echo "-- Refreshing Software repositories..."
	apt-get update  >>$0.log 2>&1
	echo "-- Installing System Updates..."
	apt-get dist-upgrade -y --force-yes >>$0.log 2>&1
	echo "-- Cleaning up unused software..."
	apt-get autoremove -y >>$0.log 2>&1
}
###########################################################################
##                                                                       ##
##                         Execute                                       ##
##                                                                       ##
###########################################################################
#
up2date
SofwareManagmentAvailabilityCHK
apt-get install landscape-client -y -q
echo "ssl_public_key = /etc/landscape/landscape_server_ca.crt" >>/etc/landscape/client.conf
echo "---------------- clinet.conf  -----------"
cat /etc/landscape/client.conf
echo "192.168.1.223       $LOCALSERVER" >>/etc/hosts
echo "----------------  hosts -----------------"
cat /etc/hosts
echo "---------  Get CA from $LOCALSERVER ---------"
echo Enter password for $LOCALSERVER below:
scp tangarora@$LOCALSERVER:/etc/landscape/*.crt /etc/landscape/
sudo landscape-config --computer-title "$HOSTNAME" --account-name standalone  -p $PASSTOKEN --url https://$LOCALSERVER/message-system --ping-url http://$LOCALSERVER/ping


