#!/bin/bash
#
#	RTD Ubuntu Scripts
#   	Stephan S.
#
#
# Version 1.00
#
# This script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it usefull.
#
# This script is instended to live in the ~/bin/ folder.

# Function
command_exists () {
    type "$1" &> /dev/null ;
}

if command_exists HandBrakeCLI ; then
    HandBrakeCLI -e x264 -b 3400 -B 160 -7 -d -R 48 -E aac+ac3 -f mp4 -4 -m -p -x bframes=3:ref=1:subme=5:me=umh:no-fast-pskip=1:trellis=1:cabac=0 -i $1 -o ~/Videos/AppleTV/$1.m4ve
  else
    echo HandBrakeCLI is not installed, attempting to install it...
    sudo add-apt-repository ppa:stebbins/handbrake-releases
    sudo apt-get update
    sudo apt install handbrake-cli
    HandBrakeCLI -e x264 -b 3400 -B 160 -7 -d -R 48 -E aac+ac3 -f mp4 -4 -m -p -x bframes=3:ref=1:subme=5:me=umh:no-fast-pskip=1:trellis=1:cabac=0 -i $1 -o ~/Videos/AppleTV/$1.m4ve
fi
