#!/bin/bash
#
#	RTD Ubuntu Scripts
#   	Stephan S.
#
#
# Version 1.00
#
# This script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
# This OEM and store nolonger exists as its owner has passed away.
# This script is shared in the hopes that someone will find it usefull.
#
# This script is instended to live in the ~/bin/ folder.


pushd /home/stephans/DVD/
for f in `ls *.iso`
do
  echo "Processing $f file..."
  HandBrakeCLI -e x264 -b 1500 -B 160 -7 -8 -R 48 -E faac -f mp4 -I -w 640 -m -x level=30:bframes=0:cabac=0:ref=1:vbv-maxrate=1500:vbv-bufsize=2000:analyse=all:me=umh:subme=6:no-fast-pskip=1 -i $f -o ~/Videos/iPod/$f.mp4
  HandBrakeCLI -e x264 -b 3200 -B 160 -7 -8 -R 48 -E aac+ac3 -f mp4 -4 -m -p -x bframes=3:ref=1:subme=5:me=umh:no-fast-pskip=1:trellis=1:cabac=0 -i $f -o ~/Videos/AppleTV/$f.m4v
  mv $f /home/stephans/DVD/Riped/
done
